version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQLD_ARGS: --bind-address=0.0.0.0
  web:
    build: .
    image: tdd_project
    command: foreman start -f Procfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
